### ISSUE TITLE
Issues running igv.js-flask

### ISSUE THREAD

**Issue by vangalamaheshh** [igvteam/igv.js-flask#10]
Hi -

I am trying to set up igv.js-flask server.
I have python3 and pip installed.

After cloning igv.js-flask.git, pip install -r requirements.txt installed all packages with out an error.

When I ran, python run.py, I get following error:

`Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from igvjs import app
  File "/usr/local/bin/igv.js-flask/igvjs/__init__.py", line 15, in <module>
    from igvjs.main import igvjs_blueprint
  File "/usr/local/bin/igv.js-flask/igvjs/main.py", line 5, in <module>
    from _config import basedir
ModuleNotFoundError: No module named '_config'`

After fixing this error by editing, igvjs/main.py with from igvjs._config import basedir, I have another error with respect to mysql,

`Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from igvjs import app
  File "/usr/local/bin/igv.js-flask/igvjs/__init__.py", line 16, in <module>
    from igvjs.ucsc import ucsc_blueprint
  File "/usr/local/bin/igv.js-flask/igvjs/ucsc.py", line 45
    except mysql.connector.Error, e:
                                ^
SyntaxError: invalid syntax`

Any help would be appreciated.

Thanks,
Mahesh

**Comment by ishanley** [comment]
Hi,

The reason you were getting those errors was that we initially were only supporting python 2. However, only some minor syntax changes were needed to support python 3 as well. It should be fixed with #11.

**Comment by vangalamaheshh** [comment]
@ishanley 👍 

Sweet, with python2.7, it works like a charm.

Thanks,
Mahesh
