### ISSUE TITLE
Visualizing BAM/BAI files from remote server

### ISSUE THREAD

**Issue by MarkleLab** [igvteam/igv.js-flask#14]
Hi!

I am trying to setup the flask server in this repo to incorporate some of the functionalities of the JS web app your team wrote. I'm done with the front end design part of it( navbar, track options, etc.). And CORS is already enabled in the config file by your team. 

My question -- how would I go about visualizing BAM/BAI files hosted on a remote server? Right now, the flask app only has the example tracks. Once I click on the load track, and select the appropriate files, they are not loaded in the IGV browser window. I've been trying to read through the files in the JS directory of igv-webapp to find the code that is responsible for this functionality, but have been unsuccessful :( 

Could you help please?

**Comment by jrobinso** [comment]
I'm not sure I understand the question.   To load remote files you need to
use URLs to the files.

**Comment by MarkleLab** [comment]
When we use IGV-webapp, users don't enter the URL of the remote file that they want to visualize. We simply click 'load track' and select it through Finder, and the app loads and visualizes the file automatically in the genome browser. 

I would like this functionality in my Flask app as well. Since the IGV-webapp can already load and visualize remote files through URLs, could you direct me to where in the code this is implemented?

**Comment by jrobinso** [comment]
That is not a remote file, the finder is selecting local files.    I suggest you do some reading on local files and javascript, particularly "Blob" type objects, to understand how that works.    You can look at the class "fileLoadWidget.js" in the js folder, but that is not a reusable class.   For loading local files you can use igv-webapp un modified, you do not need a Flask server.

For loading remote files you must use URLs,  this is documented in igv.js, look at the wiki for various track options.     A URL can be relative, i.e. not include the protocol,  if referenced from a page on the same server as the data.  I'm not an expert on Flask.

**Comment by MarkleLab** [comment]
Yes, you are right. I guess that since I connected my computer to a server through finder, files on that server are now local files. I'll read up on Blob type objects so I can manipulate these files. Thanks again for your help!
