### ISSUE TITLE
provide means to over-ride the "minified" css

### ISSUE THREAD

**Issue by petermchale** [igvteam/igv.js-flask#15]
The code at:
https://github.com/igvteam/igv.js-flask/blob/master/igvjs/static/css/igv.css
appears to do nothing as it is not imported at: 
https://github.com/igvteam/igv.js-flask/blob/master/igvjs/templates/igv.html
Instead that html file imports the minified igv.js, which, contains all the css that the app uses. 

I would either remove
https://github.com/igvteam/igv.js-flask/blob/master/igvjs/static/css/igv.css
or indicate how it may be used to override the css contained in the minified igv.js at 
https://github.com/igvteam/igv.js-flask/blob/9949b5af7f73dbb2d16277f4fdcac8ca78c1c7c3/igvjs/templates/igv.html#L12

The ability to over-ride the minified css would be a useful feature.

**Comment by jrobinso** [comment]
Thanks, good point, will amend.  I agree a means to override would be useful.   Currently you would need to  change the css in igv.js then build the distributable.

**Comment by jrobinso** [comment]
@petermchale Be careful overriding css (in igv.js).  Its not part of the public API and could change at any time.  If there are specific classes you want to customize open an issue in igv.js to discuss.

**Comment by petermchale** [comment]
Will do. Thanks.

**Comment by jrobinso** [comment]
I also updated the igv.js version to the latest release.
