### ISSUE TITLE
Tracks not rendering

### ISSUE THREAD

**Issue by helrick** [igvteam/igv.js-flask#22]
Hello, I'm running igv-flask with default settings and files but nothing appears on the BigWig or bedgraph tracks. I am not able to see any errors on the Console or Network tab of the Firefox debugger.

![Screenshot 2021-07-29 at 12 15 36](https://user-images.githubusercontent.com/47190916/127482837-32815ef6-ed64-4f8e-8908-a639fc04ba1f.png)
I also tried upgrading to the latest igv (2.9.3) but get the same behaviour. I'm running via Docker (python3.8 image) on a virtual machine. This is the output from the Flask server log:
```
* Serving Flask app 'igvjs' (lazy loading)
* Environment: development
* Debug mode: on
* Running on all addresses.
WARNING: This is a development server. Do not use it in a production deployment.
* Running on http://172.20.0.2:5000/ (Press CTRL+C to quit)
10.7.90.27 - - [29/Jul/2021 11:04:15] "GET / HTTP/1.1" 200 -
10.7.90.27 - - [29/Jul/2021 11:04:15] "GET /static/js/init.js HTTP/1.1" 200 -
10.7.90.27 - - [29/Jul/2021 11:04:16] "GET /static/img/favicon.ico HTTP/1.1" 200 -
10.7.90.27 - - [29/Jul/2021 11:04:17] "GET /static/data/public/test.bw HTTP/1.1" 206 -
10.7.90.27 - - [29/Jul/2021 11:04:17] "GET /static/data/public/test.bedGraph HTTP/1.1" 200 -
10.7.90.27 - - [29/Jul/2021 11:04:17] "GET /static/data/public/test.bw HTTP/1.1" 206 -
10.7.90.27 - - [29/Jul/2021 11:04:17] "GET /static/data/public/test.bw HTTP/1.1" 206 -
10.7.90.27 - - [29/Jul/2021 11:04:17] "GET /static/data/public/test.bw HTTP/1.1" 206 -
```

Let me know if I can provide any more information.

**Comment by jrobinso** [comment]
The test data covers only part of chromosome 1, the screenshot is on chromosome 8.

**Comment by helrick** [comment]
Ah, my mistake, thanks for the info! I can confirm that the BigWig and bedgraph tracks appear in the beginning of chromosome 1. However, the test bam file `gstt1_sample.bam` isn't showing anything with the track configuration as follows:

``` 
{
    url: 'static/data/public/gstt1_sample.bam',
    name: 'bamfile'
}
```
<img width="721" alt="Screenshot 2021-07-30 at 14 19 48" src="https://user-images.githubusercontent.com/47190916/127658846-867bc54d-4668-4f11-96ad-7ace263e5400.png">

**Comment by jrobinso** [comment]
That's because gstt1 is at locus chr22:24,374,133-24,386,311.   The
examples could be clearer about this, I will clean this up.

igv.js-flask is public as an example, but it's not maintained or further
developed.   I am not a python much less flask expert, most of my attention
now is on igv.js and igv-webapp, and of course igv desktop.
